pipeline {
    agent { label 'jenkins_agent' }

    stages {
        stage('Project') {
            steps {
                sh 'ls -ls'
                sh 'python3 --version'
                sh 'python3 Jenkins_hometasks/hometask_01_03_24/get_uniqes.py'
            }
        }
    }
}
